### ISSUE TITLE
Fix for citation bug

### ISSUE THREAD

**Issue by balrok** [ZotPlus/zotero-citations#1]
Hello I don't know how the pull requests work so here:

      req = {
        method: 'citation'
        params: [key, {style: @style}]
      }

instead of

      req = {
        method: 'citation'
        params: [@style, key]
      }

Your last commit fixed only the bibliography and this will then fix the individual citation.

On a side note: where can I find a list of allowed citation styles?
A numbered style is not possible I guess?

**Comment by AllThatIsTheCase** [comment]
Oops, sorry about that. The plugin supports any style supported by Zotero; the standard setup is explained on the [Zotero site](https://www.zotero.org/support/styles), and more styles can be downloaded and installed from the [style repository](https://www.zotero.org/styles).
