### ISSUE TITLE
Could not format references: undefined

### ISSUE THREAD

**Issue by raphael0202** [ZotPlus/zotero-citations#11]
After choosing one article with the visual 'picker', I get the following error:
'Could not format references: undefined'
By using the console, I could see that the error is triggered in schomd.coffee:36

**Comment by davepwsmith** [comment]
I can replicate this. Error reported at MGEKWAF9.

**Comment by retorquere** [comment]
David Smith dropped in a [fix](https://github.com/ZotPlus/zotero-better-bibtex/pull/350) for this, but Travis is having a major outage so I can't currently release a new Better BibTeX that would fix it. The version that I'll release as soon as Travis is back up can be found at http://tempsend.com/054A41839A

**Comment by davepwsmith** [comment]
Hmm, annoyingly that isn't the fix. Zotero still throws out:

`[JavaScript Error: "cayw:,TypeError: Zotero.BetterBibTeX.schomd.items is not a function"]`

**Comment by retorquere** [comment]
Can you try http://tempsend.com/0B6767315F ?

**Comment by davepwsmith** [comment]
That works for me. You might also want to put the 'minimize' keyword back on the URL for the atom citations plugin, else zotero takes over the screen whenever you add a citation.

**Comment by retorquere** [comment]
Ah, damn. I'll see if I can push atom to the front instead, but if not,
I'll add the minimize.

**Comment by retorquere** [comment]
0.11.2 focuses Atom after the pick, so the minimize ought not to be needed anymore. I'll close this issue when I have been able to publish BBT 1.4.7.

**Comment by raphael0202** [comment]
It works for me too with the new better bibtex version, thanks!
