### ISSUE TITLE
Pandoc Citations?

### ISSUE THREAD

**Issue by davepwsmith** [ZotPlus/zotero-citations#12]
Would it be possible to implement citations pandoc-stylee (on the basis that really a lot of academics who use markdown use pandoc because of its robust citation support)? A pandoc citation is a simple [@citekey] and the footnoting etc is dealt with afterwards.

**Comment by retorquere** [comment]
Not only possible, already present :) Go to preferences - Export - Default output format - Pandoc Citation. 

You might also want to look into [cite as you write](https://zotplus.github.io/better-bibtex/cayw.html), which can also output pandoc citations, depending on your editor of choice.

**Comment by retorquere** [comment]
Whoops, sorry, commented thinking you were in the BBT repo. So yeah, this plugin actually does two things: implement a pure-markdown citation tool, but also a way to invoke said cite-as-you-write tool.

**Comment by retorquere** [comment]
aaaand I guess you're asking whether this can be configured to pick pandoc citations instead of my scannable-cite ones. No, not currently, but when I figure out how config panes work it should be easy to add.

**Comment by davepwsmith** [comment]
So I'm sure you're already aware of this, but the documentation for that is here:

https://atom.io/docs/api/v1.2.4/Config

I'm no coder (as you've probably seen before when I've tried to help!) but I will have a look tonight and see how far I can get!

**Comment by retorquere** [comment]
I did not know this -- thanks! 0.12 has a setting that allows you to choose between atom/pandoc/mmd.
