### ISSUE TITLE
Cannot update zotero-citations for Markdown package

### ISSUE THREAD

**Issue by cjpoor** [ZotPlus/zotero-citations#14]
Hi there,
I am running Atom 1.3.2 on Mac OS X 10.10.5
When I attempt to do the available update for the zotero-citations package I get this error output:

***************************

Updating to “zotero-citations@0.12.0” failed.Hide output…
> spawn-sync@1.0.15 postinstall /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11605-33839-jxqc8a/node_modules/zotero-citations/node_modules/sync-request/node_modules/spawn-sync
> node postinstall

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-11605-33839-1pdw51g/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11605-33839-jxqc8a/npm-debug.log
***************************

No npm-debug.log was found at the location /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11605-33839-jxqc8a/npm-debug.log

however, a log file: npm-debug.log was found on an external HDD

content of this file refers to installation of tiddlywiki.

**Comment by retorquere** [comment]
Could it be [this](https://github.com/ForbesLindesay/spawn-sync/issues/28) problem?

**Comment by cjpoor** [comment]
It could be, I guess. But why does it only affect updates for the zotero-citations package? (although it was affecting updates for another package - I think bibtex-autocomplete previously).
If the issue you point to is the problem that I am getting, they appear to all be using ubuntu, so I am reluctant to try any of their fixes on my Mac.

**Comment by retorquere** [comment]
Most of them should work on a Mac, but could you see if they think this is indeed related to spawn-sync bu lodging an issue there? The error you list seems to indicate spawn-sync is at least part of the problem; you have been able to update others then?

**Comment by cjpoor** [comment]
Yes. I just updated too-bar. Other packages do not seem to provoke this
update issue.
I will post to spawn-sync page.

**Comment by retorquere** [comment]
I hope that gives us more info. I haven't been able to reproduce the issue, and I don't know where spawn-sync comes from, really; I don't have it installed, and I can't find it in the installable packages.

**Comment by cjpoor** [comment]
Did a couple more updates of packages on Atom with no issues.
Tried all steps from ForbesLindsay. Spawn-sync install now gives no errors.
However the zotero-citations updates still gives:
*********
Updating to “zotero-citations@0.12.0” failed.Hide output…

> spawn-sync@1.0.15 postinstall /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11606-1048-ruclaz/node_modules/zotero-citations/node_modules/sync-request/node_modules/spawn-sync
> node postinstall


npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-11606-1048-z05wzu/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11606-1048-ruclaz/npm-debug.log

**Comment by cjpoor** [comment]
I reported the above to ForbesLindsay.
BTW, when I run brew doctor I get:
**********
ChristophersAir:~ christopherpoor$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    python

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (7.1.1) is outdated
Please update to Xcode 7.2.
Xcode can be updated from the App Store.
*************
My system will not update Xcode and I really don't have enough knowledge at present to fix the other issues. Do you think any of these could be causing my problems with Atom and spawn-sync?

**Comment by retorquere** [comment]
I really don't know. I have atom 1.3.2 with zotero-citations 0.12.0 on on node 0.12.2 my MBA, but I'm on 10.11.5.

I've subscribed to https://github.com/ForbesLindesay/spawn-sync/issues/39 so I can follow the responses there, but it looks like it's [not just zotero-citations](https://github.com/Glavin001/atom-beautify/search?q=spawn-sync&type=Issues&utf8=%E2%9C%93) stumbling over spawn-sync. [This](https://github.com/Glavin001/atom-beautify/issues/573#issuecomment-143354959) indicates how that group solved it, but mucking about with the root acount is not something I'd recommend as a general practice, and really should not be necessary.

It looks to be related to a synchronous call I make in zotero-citations. Any change of upgrading to node 0.12 or later? That seems to take spawn-sync out of the picture.

**Comment by retorquere** [comment]
Someone else seems to have solved it by [reinstalling spawn-sync in a specific way](https://github.com/ForbesLindesay/spawn-sync/issues/11#issuecomment-102750901). Loathe to recommend doing just that -- the flag sounds a little ominous -- but perhaps the discussion is helpful.

**Comment by cjpoor** [comment]
Tried those unsafe installs etc. - no joy.
Beats me.
I am not the person to tinker with this.
Just hope citations work still.
Thanks,
Chris.

**Comment by retorquere** [comment]
Is it possible to update node to 0.12+?

**Comment by cjpoor** [comment]
Updated node already:
ChristophersAir:~ christopherpoor$ node --version
v5.2.0

**Comment by cjpoor** [comment]
No idea what all this means but FYI if any help:

hristophersAir:~ christopherpoor$ sudo npm install -g --unsafe-perm yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into
npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.5.1 postinstall /usr/local/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
/usr/local/lib
└─┬ yo@1.5.1
  ├─┬ cross-spawn-async@2.1.6
  │ └─┬ lru-cache@4.0.0
  │   └── pseudomap@1.0.2
  ├── meow@3.7.0
  └─┬ yeoman-doctor@2.1.0
    └── twig@0.8.6

**Comment by retorquere** [comment]
Ah, I had a pkg installed node, you have a brew-installed node. I'm installing that now.

**Comment by retorquere** [comment]
I'm on v5.3.0, brew-installed, and I can install and uninstall the addon at will. I really don't know what could be the problem. If you uninstall zotero-citations, can you reinstall it?

**Comment by cjpoor** [comment]
Tried uninstall and reinstall without restarting Atom. Reinstalled the .9
version OK.
Uninstalled and restarted Atom. Could not install .12 version - gave the
same error output re spawn-sync etc.

*************
Installing “zotero-citations@0.12.0” failed.Hide output…

> spawn-sync@1.0.15 postinstall /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11607-4924-1n3caj0/node_modules/zotero-citations/node_modules/sync-request/node_modules/spawn-sync
> node postinstall


npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node"
"/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js"
"--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc"
"--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install"
"/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-11607-4924-1vgukil/package.tgz"
"--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-11607-4924-1n3caj0/npm-debug.log

***************
BTW I have had a problem with minimap (shows grey bars instead of text) so
ininstalled it, restarted Atom and reinstalled it no problem (didn't solve
the issue, though :-\)

**Comment by cjpoor** [comment]
It would be interesting to see if I could install the previous version of zotero-citations (but I guess I would have to do that manually - is that possible? - and then the issue would probably not appear - ?)

**Comment by cjpoor** [comment]
I am inclined to uninstall and reinstall Atom. Don't know if that would help.

**Comment by retorquere** [comment]
How did you install .9? I can try to replay.

**Comment by cjpoor** [comment]
I assume that I originally installed zotero-citations through Atom's
package manager (npm?).
When I uninstalled and reinstalled .9 just a while ago it was also through
the Atom preferences "install" interface.

**Comment by retorquere** [comment]
I don't get to see .9 (so far)

**Comment by cjpoor** [comment]
Sorry. Your message "I don't get to see .9 (so far)" is rather cryptic to
me.

When I referred to "version .9" I was meaning your previous version of
zotero-citations for Atom Markdown. Wasn't that the version before .12? I
can't see it now because I attempted to uninstall and reinstall but could
not install the package after uninstalling it (anyway it would have
installed the current version).

**Comment by cjpoor** [comment]
I seem to have been suffering from a mental block about installing packages from the command line :-\
Installed zotero-citations 0.12.0 no problem using apm install.

**Comment by cjpoor** [comment]
It's working - with a couple of idiosyncrasies - :+1: .

**Comment by cjpoor** [comment]
Clearly, my problems stemmed from my attempting to update the package using Atom's GUI in "Preferences."
I'm happy with it as it is. Up to you if you want to check on getting your package to work with the GUI package manager.
Many thanks.

**Comment by retorquere** [comment]
I've only ever installed the package from the menu, not using apm, but in
the gui I am not offered an option to install any particular version, just
0.12. I'd love to fix it, but I haven't been able to reproduce the problem,
and the spawn-sync people don't seem to be very responsive, so I have no
idea where to start.

**Comment by cjpoor** [comment]
I left the issue open at spawn-sync so hopefully will get some answers sometime. It could be a node/nodejs issue, but that's all Greek to me. 

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by cjpoor** [comment]
I think the problem was solved by an update of Atom code.
