### ISSUE TITLE
Atom timeout?

### ISSUE THREAD

**Issue by musebrarian** [ZotPlus/zotero-citations#15]
Thanks again for your earlier quick reply, but I'm back with another question.

When using Zotero Pick, Atom complains "Editor Not Responding  Keep Waiting?"

Usually it will accept the Zotero input and go back to working after hitting enter. 

I suspect this is an Atom thing, but was wondering if you knew about a timeout setting that governs the interaction between Zotero Pick and Atom.

**Comment by retorquere** [comment]
It means BBT is taking extraordinarily long to respond. If you click http://localhost:23119/better-bibtex/cayw?format=citet, does the picker appear? Are you sure you've enabled it in BBT?

**Comment by musebrarian** [comment]
Yes, the picker does appear,  it's just I'm taking too long to  actually pick. (so an operator issue here, not a bug).   If there's a way to change the timeout I'd make it longer for myself.

**Comment by retorquere** [comment]
Huh. I'd never considered that. I'll change the picker to use async. That will prevent the editor from stalling out, but it will insert the pick whereever the cursor happens to be at time of completion.

**Comment by retorquere** [comment]
0.14 should do the right thing.
