### ISSUE TITLE
'Enable export by HTTP'

### ISSUE THREAD

**Issue by kallisons** [ZotPlus/zotero-citations#16]
I think that you hid the 'enable export by HTTP' option in Better BibTEX?

https://forums.zotero.org/discussion/35130/zotero-standalone-unavailable-chrome-win8x64/

Otherwise, there might need to be some more specific instructions about where to find it?

**Comment by retorquere** [comment]
Perhaps you are using Zotero standalone, in which case [the option is not shown], as the web server is always on in standalone.

**Comment by retorquere** [comment]
Perhaps you are using Zotero standalone, in which case [the option is not shown](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#enable-export-by-http), as the web server is always on in standalone.

**Comment by kallisons** [comment]
I am using Zotero standalone.  Thanks!
