### ISSUE TITLE
execute 'Zotero Citations: Scan'

### ISSUE THREAD

**Issue by kallisons** [ZotPlus/zotero-citations#17]
How does one execute 'Zotero Citations: Scan'?  I would guess that 'Zotero Citations' is a sub-menu under the Atom Packages menu, but I cannot find a sub-menu.  I am using Atom 1.6.2.  Maybe, there is another way to execute the scan command?

**Comment by kallisons** [comment]
Thanks!!

**Comment by ostrokach** [comment]
Had the exact same question. Was looking for 'Zotero Citations: Scan' under the 'Packages' menu...

Works great now. Thanks!!
