### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by pmlandwehr** [ZotPlus/zotero-citations#2]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:808:9)
Package.hasActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:733:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:185:24)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:355:14)
```

**Comment by RaoOfPhysics** [comment]
Pinging @retorquere. Do you know who can implement this?

**Comment by retorquere** [comment]
So this is all that's needed? https://github.com/ZotPlus/zotero-citations/commit/41b64a089dcc23266e67623cc7d4684cac2fcb7d

**Comment by RaoOfPhysics** [comment]
@retorquere: I tried that locally before pinging you but it didn't work. There are some other commands in here (https://github.com/ZotPlus/zotero-citations/blob/master/lib/zotero-citations.coffee) that pop up errors. Sadly, I don't have the skills to fix this!

**Comment by retorquere** [comment]
I'll try to see if I can get a handle on this.

**Comment by RaoOfPhysics** [comment]
@retorquere: Thank you! The plugin is very useful!

**Comment by retorquere** [comment]
OK, I think I got it to work. The new atom package is 0.3.0; it requires the latest BBT (0.11.16). I'll leave this issue open until the fix is confirmed.

**Comment by RaoOfPhysics** [comment]
@retorquere: Thanks for updating this! I have the latest version of BBT. Here's what I typed:

```markdown
[()][@bentley_academic_2011]

[#bibliography]: #
```

And here's what the plugin changed it to:

```markdown
[\(Bentley & Kyvik, 2011\)][@bentley_academic_2011]

[#bibliography]: #
```

It didn't add a bibliography, but it also didn't remove the citation marker. Let me know if you want me to run any further tests.

**Comment by pmlandwehr** [comment]
The Deprecation Cop alert is gone, which is something.

**Comment by RaoOfPhysics** [comment]
@pmlandwehr: Yup! :D

**Comment by retorquere** [comment]
@RaoOfPhysics if you open the Atom console windows (Ctrl-Alt-I) do you see any errors?

**Comment by retorquere** [comment]
If I copy-paste any of those into Atom, I do get an expanded bibliography.

**Comment by RaoOfPhysics** [comment]
@retorquere: Ok, I'll test this again by disabling all other plugins.

**Comment by retorquere** [comment]
@RaoOfPhysics: if you execute a scan with the console window open, the error might tell me all I need to know.

**Comment by RaoOfPhysics** [comment]
Still doesn't work for me. Here's what the console shows:

```
Scanning...
[@bentley_academic_2011]
Found link: [()][@bentley_academic_2011] with label () and keys @bentley_academic_2011
lookup for bentley_academic_2011
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

[#bibliography]: #
Generating bibliography for ["bentley_academic_2011"]

Object
    code: 5000
    message: "Error: undefined is not an integer-string↵_Class.prototype.integer@chrome://zotero-better-bibtex/content/keymanager.js:67:1↵_Class.prototype.get@chrome://zotero-better-bibtex/content/keymanager.js:549:15↵Zotero.BetterBibTeX.schomd.init/Zotero.CiteProc.CSL.Output.Formats.markdown["@bibliography/entry"]@chrome://zotero-better-bibtex/content/schomd.js:52:17↵CSL.Output.Queue.prototype.string@chrome://zotero/content/xpcom/citeproc.js:2945:35↵CSL.Output.Queue.prototype.string@chrome://zotero/content/xpcom/citeproc.js:2882:28↵CSL.getBibliographyEntries@chrome://zotero/content/xpcom/citeproc.js:4975:15↵CSL.Engine.prototype.makeBibliography@chrome://zotero/content/xpcom/citeproc.js:4747:11↵Zotero.BetterBibTeX.schomd.bibliography@chrome://zotero-better-bibtex/content/schomd.js:170:9↵Zotero.BetterBibTeX.endpoints.schomd.init@chrome://zotero-better-bibtex/content/web-endpoints.js:169:27↵Zotero.Server.DataListener.prototype._processEndpoint@chrome://zotero/content/xpcom/server.js:412:4↵Zotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:314:3↵Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:286:3↵Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:197:4↵"__proto__: Object
```

**Comment by retorquere** [comment]
I think that'll be sufficient, no need to disable other plugins

**Comment by retorquere** [comment]
I can't test until I'm home -- can you verify that you actually have `bentley_academic_2011` in your Zotero library? It shouldn't yield an error regardless, but it'll give me a clue on where to look.

**Comment by retorquere** [comment]
@RaoOfPhysics this is actually a different problem, I've opened issue #3 for this; please jon me there.
