### ISSUE TITLE
Missing items cause bibliography scan to fail

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-citations#3]
Can you try whether the xpi at http://zotplus.github.io/better-bibtex/#debug solves the problem for you?

**Comment by RaoOfPhysics** [comment]
Beautiful! Works almost perfectly! There's one tiny problem that was also present in previous versions: it seems that a spurious '\' is added in the DOI.

```markdown
[#bibliography]: #start
[@bentley_academic_2011]: #bentley_academic_2011 "Bentley, P., & Kyvik, S. (2011). Academic staff and public communication: a survey of popular science publishing across 13 countries. _Public Understanding of Science_, _20_(1), 48–63. http://doi.org/10.1177/0963662510384461"
<a name="bentley_academic_2011"></a>Bentley, P., & Kyvik, S. \(2011\). Academic staff and public communication: a survey of popular science publishing across 13 countries. _Public Understanding of Science_, _20_\(1\), 48–63\. http://doi.org/10\.1177/0963662510384461
[#bibliography]: #end
```

> Bentley, P., & Kyvik, S. (2011). Academic staff and public communication: a survey of popular science publishing across 13 countries. *Public Understanding of Science*, 20(1), 48–63. http://doi.org/10\.1177/0963662510384461

As you can see, the link is broken as a result.

(Btw, thanks for your quick responses to my messages!)

**Comment by retorquere** [comment]
My pleasure. Could you try the new version from the same place?

**Comment by retorquere** [comment]
BTW that the previous test version works mean that you reference a cite key somewhere that doesn't resolve; BBT handles that more gracefully now, mainly by ignoring it. You will find `??` somewhere in your text as the reference text link.

**Comment by RaoOfPhysics** [comment]
Perfect! :D

```markdown
[#bibliography]: #start
[@bentley_academic_2011]: #bentley_academic_2011 "Bentley, P., & Kyvik, S. (2011). Academic staff and public communication: a survey of popular science publishing across 13 countries. _Public Understanding of Science_, _20_(1), 48–63. http://doi.org/10.1177/0963662510384461"
<a name="bentley_academic_2011"></a>Bentley, P., & Kyvik, S. \(2011\). Academic staff and public communication: a survey of popular science publishing across 13 countries. _Public Understanding of Science_, _20_\(1\), 48–63. http://doi.org/10.1177/0963662510384461
[#bibliography]: #end
```

> Bentley, P., & Kyvik, S. (2011). Academic staff and public communication: a survey of popular science publishing across 13 countries. *Public Understanding of Science*, 20(1), 48–63. http://doi.org/10.1177/0963662510384461

**Comment by RaoOfPhysics** [comment]
> that the previous test version works mean that you reference a cite key somewhere that doesn't resolve

I've checked the cite keys, but I'll double check anyway. Thanks once again! :)

**Comment by retorquere** [comment]
I've scheduled 0.13.5 for release, but Travis is having issues. When https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/67999740 completes, it will automatically release the version.

**Comment by RaoOfPhysics** [comment]
@retorquere: Thank you for this. :)

**Comment by retorquere** [comment]
(bows) you're welcome.
