### ISSUE TITLE
consider merging with autocomplete bibtex

### ISSUE THREAD

**Issue by mangecoeur** [ZotPlus/zotero-citations#4]
Just wondering if you were aware of https://github.com/apcshields/autocomplete-bibtex and whether you might consider merging your project with that one? There's already an open issue there for better integration with Zotero...

**Comment by retorquere** [comment]
This package does things very differently; I suspect users who'd want to use autocomplete-bibtex prefer to have the bibliography management not change their source document. For better integration with Zotero, looks like @adunning is already on it with https://github.com/apcshields/autocomplete-bibtex/issues/31; I'd put more stock in that approach. I also write the Better BibTeX extension @adunning refers to there -- any changes that need to be made to facilitate that connection I'll be glad to take on.

**Comment by adunning** [comment]
I am tempted to suggest replacing this plugin with something that simply calls your new Cite as you Write functionality. I have something for my own setup that does this, but it's not fit for public consumption (at the very least, I would need to set up the settings properly to make the parameters configurable).

**Comment by retorquere** [comment]
These approaches could all be complimentary to this plug-in; the others offer better pickers (this one offers none, so that's easy), but this one requires no outside processors like mmd or pandoc - all the bibliography generation is fully inside atom (well...), and the results will render anywhere where pandoc will.

**Comment by adunning** [comment]
Thanks for the explanation; it's a neat idea.
