### ISSUE TITLE
zotero-citations does not see references unless they are selected first in Zotero

### ISSUE THREAD

**Issue by igravious** [ZotPlus/zotero-citations#5]
```javascript
 > atom.packages.isPackageLoaded('zotero-citations')
true
 > atom.packages.isPackageActive('zotero-citations')
false
```

I have no idea what I've done (if anything) to cause it to stop working. I don't know where to start to debug what is going on. Help!

**Comment by retorquere** [comment]
Could you try upgrading to atom 1.0.7 first?

**Comment by igravious** [comment]
Okay, seems to work in 1.0.7. but... But (and this is very strange and had/has me puzzled) I had to go into Zotero in Firefox and click on each citation individually to get Z-B-B add-on to talk to send data back to the z-c Atom package. Very very odd, something weird going on there.

I should check that Atom version 1.0.0 works also, as that is what most Linux users will have as Atom does not auto-upgrade like MacOSX and Windows I believe. You're pretty sure z-c version 0.3.0 works with Atom version 1.0.0?

**Comment by retorquere** [comment]
What would happen if you didn't click those references?

I am not sure whether z-c works with atom 1.0.0, and your case seems to indicate it doesn't. Atom keeps changing the internal APIs; I only support the latest version because of this, as my time is extremely limited.

**Comment by retorquere** [comment]
I think I may have found a cause, could you try installing http://tempsend.com/008A536426

**Comment by retorquere** [comment]
1.2.32 has the fix; please re-open if it doesn't work.

**Comment by igravious** [comment]
Oh sorry, didn't notice these notifications!

I have tried z-c version 0.7.0 Atom package with Z-B-B Firefox add-on on Atom version 1.0.7. This works first time for me. Did my vague bug report give you a clue?

You can leave this closed but could I say one thing? Most Linux users are going to be on Atom Version 1.0.0 I believe because there is no automatic upgrade for the default Atom install on Linux. So, you'll probably need a version of z-c that works with Atom version 1.0.0 or perhaps you'll need to advise people to track the latest Atom. Otherwise you're going to be getting bug reports like mine :)

So on Ubuntu to track Atom I use the http://ppa.launchpad.net/webupd8team/atom/ubuntu repo.

**Comment by retorquere** [comment]
I'm pleased it works for you, and yes, there was enough information to figure it out - it was a somewhat subtle bug. 

I understand linux users (like myself) will not get automatic updates for the most part, but as my time is limited (and I don't use atom myself), I can only support one version. Since the documentation for atom tracks the latest version, that's what I support. I don't mind extra issue reports, but I don't have the time for older versions.

**Comment by igravious** [comment]
Understood. I appreciate your time is limited, and I appreciate the work you're doing. I will track the latest Atom.
